### ISSUE TITLE
5. úkol

### ISSUE THREAD

**Issue by DanielaAntosova** [DanielaAntosova/python_jaro_2022#5]
https://github.com/DanielaAntosova/python_jaro_2022/blob/main/ukol-5.py

Ahoj Moni,

zde posílám odkaz na 5. úkol :) Díky!

Hezký zbytek týdne

Danča

**Comment by MonikaDvorackova** [comment]
Ahoj Dani, 

skvělé, bez problému, vše správně. Moc děkuju za tak brzké odevzdání, jsi hrozně šikovná.

Měj se hezky,
Monika
